### DISCUSSION TITLE
Openapi で any な型を定義

### DISCUSSION THREAD

**Discussion by morx3x** [morx3x/sushi#8] [Programming]
- using empty schema
```
# swagger: '2.0'
definitions:
  AnyValue: {}

# openapi: 3.0.0
components:
  schemas:
    AnyValue: {}
```

- using description

```

# swagger: '2.0'
definitions:
  AnyValue:
    description: 'Can be anything: string, number, array, object, etc. (except `null`)'

# openapi: 3.0.0
components:
  schemas:
    AnyValue:
      description: 'Can be anything: string, number, array, object, etc., including `null`'

```

https://stackoverflow.com/questions/32841298/openapi-what-schema-to-accept-any-complex-json-value
